---
- name: Create users
  hosts: servera
  become: true

  vars:

    myusers:
      - fred
      - barney
      - wilma
      - betty

    mystate: present

  tasks:

    - name: Ensure users are {{ mystate }}
      loop: "{{ myusers }}"
      user:
        name: "{{ item }}"
        state: "{{ mystate }}"
...
