- name: Gather and display facts
  hosts: 
    - ios
    - junos      
  gather_facts: true
  become: false

  tasks:

    - name: Ensure facts are displayed
      ansible.builtin.debug:
        var: ansible_facts

    - name: Ensure serial number is displayed
      ansible.builtin.debug:
        msg: |
          "{{ inventory_hostname }} has serial number {{ ansible_facts['net_serialnum'] }}"

    - name: Ensure conditional based on fact
      when: ansible_facts['net_version'] == "23.1R1.8"
      ansible.builtin.debug:
        msg: | 
          Fixing {{ inventory_hostname }} due to version {{ ansible_facts['net_version'] }} being associated with security vulnerabilities

