#!/bin/bash
myuser=john
myuid=10000
myshell=/bin/bash

if [ "$(getent passwd ${myuser} | awk -F: '{print $1}')" = "${myuser}" ]
        then
           echo "The user ${myuser} exists"
        else
           useradd -u ${myuid} ${myuser}
           echo $?
fi

if [ "$(getent passwd ${myuser} | awk -F: '{print $3}')" -ne "${myuid}" ]
        then
            usermod -u ${myuid} ${myuser}
        else
           echo "The user ${myuser} exists with ${myuid}"
fi


