- name: Configure login banners
  hosts: ios
  gather_facts: false

  tasks:

    - name: Ensure banner is configured on IOS devices
      notify: Ensure changes are saved 
      cisco.ios.ios_banner:
        banner: login
        text: Managed by Ansible Automation Platform
        state: present

  handlers:

    - name: Ensure changes are saved
      cisco.ios.ios_config:
        save_when: always
