---
- name: Gather and display facts for Cisco Network Devices
  hosts: ios
  become: true
  gather_facts: false

  tasks:

    - name: Ensure IOS facts are gathered
      when: ansible_network_os == 'ios'
      cisco.ios.ios_facts:

    - name: Ensure specified commands are run
      register: ios_output
      cisco.ios.ios_command:
        commands:
          - show version
          - show ip int brief

    - name: Ensure output is displayed
      ansible.builtin.debug: 
        var: ios_output
