- name: Backup IOS XE configurations
  hosts: ios
  gather_facts: false

  tasks:

    - name: Ensure backup directory exists
      run_once: true
      ansible.builtin.file:
        path: backups
        state: directory

    - name: Ensure configuration backup is taken 
      cisco.ios.ios_config:
        backup: true
        backup_options:
          dir_path: backups/
          filename: "{{ inventory_hostname }}.txt"
