- name: Gather and display variables
  hosts: ios
  order: sorted
  gather_facts: false

  tasks:
    
    - name: Display variable types
      ansible.builtin.debug:
        var: interfaces | type_debug

    - name: Display variable for type single element
      ansible.builtin.debug:
        var: interfaces['iosxe1.lab.example.com'] | type_debug

    - name: Display variable value for single element
      when: inventory_hostname == 'iosxe1.lab.example.com'
      ansible.builtin.debug:
        var: interfaces['iosxe1.lab.example.com'] 

    - name: Display variable for single element (Data Type)
      when: item == inventory_hostname
      loop: "{{ interfaces | list }}"
      ansible.builtin.debug:
        var: interfaces[item] | type_debug

    - name: Display variable for single element (Data Value)
      when: item == inventory_hostname
      loop: "{{ interfaces | list }}"
      ansible.builtin.debug:
        var: interfaces[item] 

    - name: Accessing Values for Configuration from a List
      when: item == inventory_hostname
      loop: "{{ interfaces | list }}"
      ansible.builtin.debug:
        msg: |
          "Inventory host: {{ inventory_hostname }}
          Interfaces available: {{ interfaces[item]| map(attribute='name') }}.
          IP addresses: {{ interfaces[item]| map (attribute='ipv4') }}."

    - name: Accessing a specific Value for Configuration from a List
      loop: "{{ interfaces[inventory_hostname] }}"
      ansible.builtin.debug:
        msg: |
          "Inventory host: {{ inventory_hostname }}
          Interface {{ item['name'] }} will have IP Address {{ item['ipv4'] }}."
