---
- name: Gather and display facts for Cisco Network Devices
  hosts: ios
  become: false
  gather_facts: false

  tasks:
    
    - name: Ensure ICMP connectivity to {{ inventory_hostname }} 
      when: ansible_network_os == 'ios'
      cisco.ios.ios_ping:
        dest: "{{ inventory_hostname }}"
        count: 5
