- name: Demonstrate variable precedence
  hosts: localhost
  gather_facts: false
  become: false

  vars:

    my_string: yellow

  vars_files:

    - general.yml

  tasks:

    - name: Ensure fact controller learns about my_string
      ansible.builtin.set_fact:
        my_string: indigo

    - name: Ensure variable is displayed
      vars:
        my_string: blue
      ansible.builtin.debug:
        msg: The value of the variable my_string is {{ my_string }}

- name: This is another play
  hosts: localhost
  gather_facts: false
  become: false

  tasks: 
    
    - name: Ensure variable from the previous play is displayed
      ansible.builtin.debug:
        var: my_string
