---
- name: Gather and display facts for Cisco Network Devices
  hosts: ios, workstation
  become: true
  gather_facts: false
  tasks:
    - name: Test Connectivity using the Ping Module
      tmichett.do457_demo_collection.ios_ping:
        dest: "{{ inventory_hostname }}"
        count: 5
      when: ansible_network_os == 'cisco.ios.ios'

    - name: Test Connectity using the Ping Module
      tmichett.do457_demo_collection.ping:
