---
- name: Setup the support infrastructure to manage systems
  hosts: all 
  gather_facts: true
  
  tasks:

    - name: Show the OS type
      debug:
        msg: My name is {{ ansible_facts['hostname'] }} and I am a {{ ansible_facts['system'] }} system running {{ ansible_facts['distribution'] }}
...
