my_acl:
  - acls:
      - name: junos_acl
        aces:
          - name: permit_igmp
            grant: permit
            protocol: igmp
            source:
              address: 172.25.250.100/32
          - name: bgp_12
            source:
              address:
                - 12.0.0.0/16
                - 12.1.0.0/16
              port_protocol:
                eq: bgp
            protocol: tcp
          - name: allow_ssh
            source:
              port_protocol:
                eq: ssh
            protocol: tcp
    afi: ipv4

my_search:
  - lab.example.com
  - example.com

my_dns:
  - 172.25.250.220

my_location: Westford, MA 
my_contact: 'Network Engineering | neteng@example.com'
my_communities:
  - name: rocommunity2n4g!
    authorization: read-only
  - name: rwcommunityd7g$v
    authorization: read-write
