- name: Create users in the appropriate groups
  hosts: servera
  become: true
  no_log: false

  vars_files:
    - hash_dictionary_vars.yml

  tasks:

    - name: Ensure groups are created
      loop: "{{ mygroups }}"
      group:
        name: "{{ item }}"
        state: present

    - name: Ensure users are in their appropriate groups
      loop: "{{ myusers | dict2items }}"
      user:
        name: "{{ item['key'] }}"
        state: present
        groups: "{{ item['value']['groups'] }}"
        password: "{{ item['value']['password'] | password_hash('sha512') }}"
        update_password: on_create
        generate_ssh_key: true
