- name: Create and list Organizations
  hosts: localhost

  tasks:

    - name: Ensure organization is created
      redhat.satellite.organization:
        server_url: "{{ sat_api }}"
        username: "{{ sat_user }}"
        password: "{{ sat_pass }}"
        validate_certs: "{{ cert_validate }}"
        name: "{{ sat_org | mandatory }}"
        state: present

    - name: List Satellite Organizations
      register: sat_orgs
      redhat.satellite.organization_info:
        server_url: "{{ sat_api }}"
        username: "{{ sat_user }}"
        password: "{{ sat_pass }}"
        validate_certs: "{{ cert_validate }}"
        search: " "

    - name: Print List of Satellite Organizations
      ansible.builtin.debug:
        msg: "{{ sat_orgs['organizations'] | map(attribute='name') | list }}"
