---
- name: Add topology segments
  hosts: ipaserver
  become: true
  gather_facts: false

  vars:
    ipatopology_segments:
    - suffix: domain+ca
      left: idm.lab.example.com
      right: replica1.lab.example.com
    - suffix: domain
      left: replica1.lab.example.com
      right: replica2.lab.example.com

  tasks:
  - name: Ensure topology segment is configured
    loop: "{{ ipatopology_segments | default([]) }}"
    ipatopologysegment:
      password: "{{ ipaadmin_password }}"
      suffix: "{{ item['suffix'] }}"
      name: "{{ item['name'] | default(omit) }}"
      left: "{{ item['left'] }}"
      right: "{{ item['right'] }}"
      state: reinitialized
