# Artur Glogowski <aglogows@redhat.com>

- hosts: "{{ server }}"

  vars:
    ipa_server: idm.lab.example.net
    ipa_server_ip: 172.25.250.8
    ipa_domain: lab.example.net
    ipa_realm: LAB.EXAMPLE.NET
    ipa_admin_password: RedHat123^

  tasks:

    #- name: Disable Network Manager DNS management
    #  ini_file:
    #    path: /etc/NetworkManager/NetworkManager.conf
    #    section: main
    #    option: dns
    #    value: none
      
    - name: Install required packages
      yum: name={{ item }} state=installed
      with_items:
      - NetworkManager-glib
      - nm-connection-editor.x86_64
      - libsemanage-python
      - policycoreutils-python
      
    - name: Change network settings
      nmcli:
        conn_name: "System eth0"
        ifname: eth0
        type: ethernet
        ip4: "{{ ip }}"
        state: present
        dns4: 172.25.250.254
        autoconnect: yes

    - name: Remove default gw
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        state: absent
        regexp: '^GATEWAY='
 
    - name: Changing ipv4.gateway setting
      command: nmcli connection modify "System eth0" ipv4.gateway 0.0.0.0

    - name: Reload new configuration
      command: nmcli connection up "System eth0"
   
    - name: Restarting NetworkManager
      service: 
        name: NetworkManager
        state: restarted

    - name: Remove default gw
      command: route del default gw 172.25.250.254
      ignore_errors: true
    
    - name: Add routing to example.com network
      command: route add -net 172.25.254.0/24 gw 172.25.250.254
