# uninstall_ipa_client.yml
# Chen Chang <cchang@redhat.com>

- hosts: "{{ ipa_client }}"

  vars:
    ipa_server: ipa.lab.example.net
    ipa_server_ip: 172.25.250.8
    ipa_domain: lab.example.net
    ipa_realm: LAB.EXAMPLE.NET
    ipa_admin_password: RedHat123^
    ipa_client_packages: 
      - ipa-client

  tasks:

    - name: IPA client packages installed
      package:
        name: "{{ item }}"
        state: latest
      with_items: "{{ ipa_client_packages }}"

    - name: Disable Network Manager DNS management
      ini_file:
        path: /etc/NetworkManager/NetworkManager.conf
        section: main
        option: dns
        value: none

    - name: Set DNS server to IPA server
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver '
        line: "nameserver {{ ipa_server_ip }}"
            
    - name: Get Kerberos credentials as IPA admin
      shell: echo "{{ipa_admin_password }}" | kinit -f admin
      ignore_errors: yes
      register: cred_result
      changed_when: false

    - name: Uninstall IPA client
      command: ipa-client-install  --uninstall
      when: "'kinit: Configuration file does not specify default realm when parsing name admin' not in cred_result.stderr"
