- name: Ensure ACLs are configured 
  loop: "{{ my_acl }}"
  loop_control:
    loop_var: my_acl_item
  junipernetworks.junos.junos_acls:
    state: overridden
    config: 
      - "{{ my_acl_item }}"
