- name: password_hash filter demonstration
  hosts: servera 
  gather_facts: false
  become: true

  tasks:

    - name: Ensure user at specified state
      ansible.builtin.user:
        name: "{{ my_user | default('ansible') }}"
        password: "{{ my_password | default('redhat') | password_hash('sha512') }}"
        groups: "{{ my_groups | default(omit) }}"
        state: "{{ my_state | default('present') }}"
        update_password: on_create
