---
- name: Gather and display facts
  hosts: ios
  order: sorted
  gather_facts: false
  tasks:
    - name: Display Variable types
      ansible.builtin.debug:
        var: interfaces | type_debug

    - name: Display Variable for type single element
      ansible.builtin.debug:
        var: interfaces['iosxe1.lab.example.com'] | type_debug

    - name: Display Variable value for single element
      ansible.builtin.debug:
        var: interfaces['iosxe1.lab.example.com'] 

    - name: Display Variable for single element (Data Type)
      ansible.builtin.debug:
        var: interfaces[item] | type_debug
      loop: "{{ interfaces | list }}"
      when: item == inventory_hostname

    - name: Display Variable for single element (Data Value)
      when: item == inventory_hostname
      loop: "{{ interfaces | list }}"
      ansible.builtin.debug:
        var: interfaces[item] 

    - name: Accessing Values for Configuration from a List
      when: item == inventory_hostname
      loop: "{{ interfaces | list }}"
      ansible.builtin.debug:
        msg: |
          "Inventory host: {{ inventory_hostname }}
         Interfaces available: {{ interfaces[item]| map(attribute='name') }}.
        IP addresses: {{ interfaces[item]| map (attribute='ipv4') }}."

    - name: Accessing a specific Value for Configuration from a List
      loop: "{{ interfaces[inventory_hostname] }}"
      ansible.builtin.debug:
        msg: |
          "Inventory host: {{ inventory_hostname }}
          Interface {{ item['name'] }} will have IP Address {{ item['ipv4'] }}."
