- name: Ensure netconf service is enabled 
  vars:
    ansible_connection: ansible.netcommon.network_cli
  junipernetworks.junos.junos_netconf:
    netconf_port: 830
    state: present

- name: Verify connectivity
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 830
    timeout: 5
