- name: Manage software 
  hosts: all
  vars:
    pkg_name:
    pkg_state:

  tasks:

    - name: Ensure {{ pkg_name }} is {{ pkg_state }}
      yum:
        name: "{{ pkg_name | default('yum', true) }}"
        state: "{{ pkg_state | default('installed', true) }}"
