- name: Demonstrate globbing
  hosts: localhost
  become: false
  gather_facts: false

  vars:
        my_files: "{{ query('fileglob', '/etc/v*rc') }}"
    

  tasks:

    - name: Ensure v*rc file contents are listed
      vars:
        my_content: "{{ lookup('file', my_files) }}"
      loop: "{{ my_content }}"
      ansible.builtin.debug:
        msg: "{{ item }}"

