- name: Demonstrate globbing
  hosts: localhost
  become: false
  gather_facts: false

  tasks:

    - name: Ensure v*rc file contents are listed
      ansible.builtin.debug:
        msg: "{{ query('fileglob', '/etc/v*rc') }}"
