- name: Demonstrate ordering
  hosts: all
  order: reverse_sorted
  become: false
  gather_facts: false

  tasks:

    - name: Display current inventory host
      ansible.builtin.debug:
        var: inventory_hostname
