- name: Populate users from a file
  hosts: all
  gather_facts: false
  become: true

  tasks:

    - name: Ensure remote user is created
      vars:
        my_password: "{{ lookup('password', 'credentials/' + item + ' length=9') }}"
      loop: "{{ query('lines','cat users.txt') }}"
      user:
        name: "{{ item }}"
        state: "{{ my_state | default('present') }}"
        password: "{{ my_password | password_hash('sha512') }}"
        update_password: on_create

    - name: Ensure text message is sent to user with password
      some_module:
        lookup('file', 'credentials/' + item)

    - name: Ensure password file is deleted
      file:
        file: "{{ lookup('file', 'credentials/' + item) }}"
        state: absent
