#!/bin/bash
#
# Copyright 2017 Red Hat, Inc.
#
# NAME
#     demo-rest-api - grading script for RH362 Programming REST API demonstration
#
# SYNOPSIS
#     demo-rest-api {setup|cleanup}
#
#        setup   - prepare the system for starting the lab
#        cleanup - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does setup, grading,
#     cleanup, or solve.
#
# CHANGELOG
#   * Thu Feb 23 2018 Morgan Weetman <mweetman@redhat.com>
#   - original code


PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='workstation'
materials='http://materials.example.com'

# This defines which subcommands are supported (setup, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(setup cleanup)

function lab_setup {

  print_header "Setting up ${target} for lab exercise work:"

  pad ' . Ensuring IdM services are ready: '
  if idm_service_ready
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad ' . Creating demo user: '
  if ${ssh} root@idm "echo RedHat123^ | kinit admin && ipa user-add demo --first Dr --last Demo --email demo@lab.example.net --shell /bin/bash"
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad ' . Downloading JSON request payload file: '
  if ${ssh} root@idm "curl -O ${materials}/labs/req_show_demo.json"
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  print_line

}

function lab_cleanup {

  print_header "Cleaning up the lab on ${target}:"

  pad ' . Deleting demo user: '
  if ${ssh} root@idm "echo RedHat123^ | kinit admin && ipa user-del demo"
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad ' . Deleting JSON request payload file: '
  if ${ssh} root@idm "rm -f /root/req_show_demo.json /root/idm_cookies.txt"
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  print_line
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
