#!/bin/bash
#
# Copyright 2017 Red Hat, Inc.
#
# NAME
#     lab-rest-api - grading script for RH362 Programming REST API exercise
#
# SYNOPSIS
#     lab-rest-api {setup|cleanup}
#
#        setup   - prepare the system for starting the lab
#        cleanup - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does setup, grading,
#     cleanup, or solve.
#
# CHANGELOG
#   * Sun Mar 18 2018 Victor Costea <vcostea@redhat.com>
#   - Add check and set code
#   * Thu Feb 16 2018 Morgan Weetman <mweetman@redhat.com>
#   - original code


PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='workstation'
materials='http://materials.example.com'
title="Programming with the Management Interface"
lab_directory_name='central-api'

# This defines which subcommands are supported (setup, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(setup cleanup)


function lab_setup {

  print_header "Setting up ${target} for lab exercise work:"

  idm_base_state
  my_grab_lab_files 'no-solution'
  chmod 600 /home/student/${RHT_COURSE^^}/labs/${lab_directory_name}/*

  pad ' . Downloading JSON request payload files: '
  if cd /home/student && curl -O -O -O ${materials}/labs/req_{show_admin,mod_admin,env}.json
  then
    if chown student:student /home/student/req_*.json
    then
      print_SUCCESS
    else
      print_FAIL
    fi
  else
    print_FAIL
  fi

  print_line
}

function lab_cleanup {

  print_header "Cleaning up the lab on ${target}:"

  pad ' . Deleting JSON request payload files: '
  if rm -f /home/student/req_*.json /home/student/idm_cookies.txt
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  print_line
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
