- name: Ensure needed variables are defined
  tags:
    - always
  assert:
    that:
      - (my_package == "httpd") or (my_package == "nginx" )
    success_msg: |
    
      The needed variables are set, proceeding
    
    fail_msg: |
    
      OH NO! We need to set my_package to either httpd or nginx

- name: Ensure setup tasks are included
  include_tasks: setup_tasks.yml
