- name: Ensure {{ my_package }} is installed
  yum:
    name: "{{ my_package }}"
    state: latest 

- name: Ensure {{ my_package }} is started and enabled 
  systemd:
    name: "{{ my_package }}"
    enabled: true
    state: started

- name: Ensure service is allowed in firewall
  loop: "{{ my_services }}"
  firewalld:
    service: "{{ item }}"
    immediate: true
    permanent: true
    state: enabled

- name: Ensure stub content is installed for httpd
  when: my_package == "httpd"
  copy:
    content: "{{ my_content }}"
    dest: /var/www/html/index.html

- name: Ensure stub content is installed for nginx
  when: my_package == "nginx"
  copy:
    content: "{{ my_content }}"
    dest: /usr/share/nginx/html/index.html
    
