- name: Ensure {{ my_package }} is stopped and disabled 
  ignore_errors: true
  systemd:
    name: "{{ my_package }}"
    enabled: false
    state: stopped

- name: Ensure {{ my_package }} is removed
  yum:
    name: "{{ my_package }}"
    state: absent 

- name: Ensure service is removed from firewall
  loop: "{{ my_services }}"
  firewalld:
    service: "{{ item }}"
    immediate: true
    permanent: true
    state: disabled

- name: Ensure stub content is removed from httpd
  when: my_package == "httpd"
  file:
    state: absent
    dest: /var/www/html/index.html

- name: Ensure stub content is removed from nginx
  when: my_package == "nginx"
  file:
    state: absent
    dest: /usr/share/nginx/html/index.html
